import {
  ScanSearch,
  CircleDot,
  Truck,
  Bell,
} from "lucide-react";

export const AOI_STATS = [
  {
    id: "total",
    icon: ScanSearch,
    value: "12",
    subtitle: "2 Inactive",
    title: "Total AOIs",
    accent: "red",
  },
  {
    id: "active",
    icon: CircleDot,
    value: "10",
    subtitle: "Monitoring enabled",
    title: "Active AOIs",
    accent: "orange",
  },
  {
    id: "vehicles",
    icon: Truck,
    value: "38",
    subtitle: "Across all AOIs",
    title: "Vehicles Covered",
    accent: "yellow",
  },
  {
    id: "alerts",
    icon: Bell,
    value: "7",
    subtitle: "Entry & exit events",
    title: "Alerts Today",
    accent: "green",
  },
];

export const AOI_FILTERS = [
  { label: "All", value: "all", color: "bg-[#71717a]" },
  { label: "Active", value: "active", color: "bg-[#10b981]" },
  { label: "Inactive", value: "inactive", color: "bg-[#FDBB24]" },
];

export const AOI_LIST = [
  {
    id: 1,
    name: "Mumbai Warehouse",
    type: "Circular",
    size: "2.5 km radius",
    vehicles: 8,
    status: "active",
    color: "#FDBB24",
    center: [19.1136, 72.8697],
    radiusMeters: 2500,
    createdBy: "Wade Warren",
    createdAt: "12 Jun 2026",
    inside: 5,
    enteredToday: 3,
    exitedToday: 2,
    assignedVehicles: [
      { plate: "MH12AB3482", status: "Inside" },
      { plate: "MH14ZZ8765", status: "Inside" },
      { plate: "MH12CD9012", status: "Outside" },
      { plate: "MH15EF4455", status: "Inside" },
    ],
  },
  {
    id: 2,
    name: "Pune Distribution Center",
    type: "Circular",
    size: "1.8 km radius",
    vehicles: 6,
    status: "active",
    color: "#a855f7",
    center: [18.5912, 73.7389],
    radiusMeters: 1800,
    createdBy: "Leslie Alexander",
    createdAt: "28 May 2026",
    inside: 4,
    enteredToday: 2,
    exitedToday: 1,
    assignedVehicles: [
      { plate: "MH09XY1234", status: "Inside" },
      { plate: "MH04GH7788", status: "Outside" },
      { plate: "MH09KL5566", status: "Inside" },
    ],
  },
  {
    id: 3,
    name: "Nashik Hub",
    type: "Polygon",
    size: "4.2 km²",
    vehicles: 5,
    status: "active",
    color: "#3b82f6",
    center: [19.9975, 73.7898],
    radiusMeters: 2100,
    createdBy: "Atul",
    createdAt: "04 Jun 2026",
    inside: 3,
    enteredToday: 1,
    exitedToday: 0,
    assignedVehicles: [
      { plate: "MH12IJ3344", status: "Inside" },
      { plate: "MH15NP2233", status: "Outside" },
    ],
  },
  {
    id: 4,
    name: "Thane Yard",
    type: "Circular",
    size: "1.2 km radius",
    vehicles: 4,
    status: "inactive",
    color: "#71717a",
    center: [19.2183, 72.9781],
    radiusMeters: 1200,
    createdBy: "Wade Warren",
    createdAt: "18 Apr 2026",
    inside: 0,
    enteredToday: 0,
    exitedToday: 0,
    assignedVehicles: [
      { plate: "MH04QR8899", status: "Outside" },
      { plate: "MH12ST6677", status: "Outside" },
    ],
  },
  {
    id: 5,
    name: "Delhi Depot",
    type: "Circular",
    size: "3.0 km radius",
    vehicles: 7,
    status: "active",
    color: "#10b981",
    center: [28.6139, 77.209],
    radiusMeters: 3000,
    createdBy: "Leslie Alexander",
    createdAt: "02 Jul 2026",
    inside: 4,
    enteredToday: 4,
    exitedToday: 3,
    assignedVehicles: [
      { plate: "DL03AB1122", status: "Inside" },
      { plate: "DL05CD3344", status: "Inside" },
      { plate: "DL01EF5566", status: "Outside" },
    ],
  },
  {
    id: 6,
    name: "Chennai Port Zone",
    type: "Polygon",
    size: "5.1 km²",
    vehicles: 8,
    status: "inactive",
    color: "#f59e0b",
    center: [13.0827, 80.2707],
    radiusMeters: 2200,
    createdBy: "Atul",
    createdAt: "10 Mar 2026",
    inside: 0,
    enteredToday: 0,
    exitedToday: 0,
    assignedVehicles: [
      { plate: "TN09GH7788", status: "Outside" },
    ],
  },
];
