import {
  TriangleAlert,
  ShieldAlert,
  Bell,
  FileCheck,
  Zap,
  KeyRound,
  WifiOff,
  BatteryLow,
  Wrench,
  MapPinned,
  Gauge,
  Activity,
  Siren,
  Truck,
  Pause,
  Fuel,
  Thermometer,
} from "lucide-react";

export const FLEET_OPTIONS = [
  { label: "All Fleets", value: "all" },
  { label: "Mumbai Fleet", value: "mumbai" },
  { label: "Pune Fleet", value: "pune" },
  { label: "Nashik Fleet", value: "nashik" },
];

export const SEVERITY_OPTIONS = [
  { label: "All Severity", value: "all" },
  { label: "Critical", value: "critical" },
  { label: "High", value: "high" },
  { label: "Medium", value: "medium" },
  { label: "Low", value: "low" },
];

export const ALERT_STATS = [
  {
    id: "total",
    icon: TriangleAlert,
    value: "24",
    subtitle: "3 Critical, 8 High",
    title: "Total Alerts",
    accent: "red",
  },
  {
    id: "critical",
    icon: ShieldAlert,
    value: "3",
    subtitle: "Requires immediate attention",
    title: "Critical Alerts",
    accent: "red",
  },
  {
    id: "new",
    icon: Bell,
    value: "2",
    subtitle: "Not yet reviewed",
    title: "New Alerts",
    accent: "yellow",
  },
  {
    id: "resolved",
    icon: FileCheck,
    value: "14",
    subtitle: "Issues handled",
    title: "Resolved",
    accent: "green",
  },
];

export const ALERT_TYPES = [
  { id: "power-cut", label: "Power Cut", icon: Zap, count: 3 },
  { id: "ignition", label: "Ignition On/Off", icon: KeyRound },
  { id: "no-data", label: "No Data", icon: WifiOff },
  { id: "low-battery", label: "Low Battery", icon: BatteryLow },
  { id: "tampering", label: "Tampering", icon: Wrench },
  { id: "geofence", label: "Geofence Entry/Exit", icon: MapPinned },
  { id: "overspeed", label: "Overspeed", icon: Gauge },
  {
    id: "harsh",
    label: "Harsh Acceleration/Braking/Cornering",
    icon: Activity,
  },
  { id: "sos", label: "SOS / Panic", icon: Siren },
  { id: "towing", label: "Towing", icon: Truck },
  { id: "idle", label: "Idle", icon: Pause },
  { id: "fuel", label: "Fuel Drain/Refill", icon: Fuel },
  { id: "temperature", label: "Temperature", icon: Thermometer },
];

export const RECENT_ALERTS = [
  {
    id: 1,
    dateTime: "06 Jul 2026, 09:42 AM",
    vehicle: "MH12AB3482",
    driver: "Ashok Sharma",
    location: "Andheri East, Mumbai",
    recordedSpeed: 92,
    speedLimit: 60,
    status: "High",
    type: "overspeed",
    fleet: "mumbai",
  },
  {
    id: 2,
    dateTime: "06 Jul 2026, 09:18 AM",
    vehicle: "MH09XY1234",
    driver: "Rahul Singh",
    location: "Hinjewadi, Pune",
    recordedSpeed: 48,
    speedLimit: 60,
    status: "Medium",
    type: "idle",
    fleet: "pune",
  },
  {
    id: 3,
    dateTime: "06 Jul 2026, 08:55 AM",
    vehicle: "MH14ZZ8765",
    driver: "Suresh Patil",
    location: "Bandra West, Mumbai",
    recordedSpeed: 0,
    speedLimit: 40,
    status: "High",
    type: "power-cut",
    fleet: "mumbai",
  },
  {
    id: 4,
    dateTime: "06 Jul 2026, 08:30 AM",
    vehicle: "MH12CD9012",
    driver: "Vikram Joshi",
    location: "CIDCO, Nashik",
    recordedSpeed: 74,
    speedLimit: 50,
    status: "High",
    type: "overspeed",
    fleet: "nashik",
  },
  {
    id: 5,
    dateTime: "06 Jul 2026, 07:48 AM",
    vehicle: "MH15EF4455",
    driver: "Ramesh Kumar",
    location: "Powai, Mumbai",
    recordedSpeed: 35,
    speedLimit: 60,
    status: "Medium",
    type: "geofence",
    fleet: "mumbai",
  },
  {
    id: 6,
    dateTime: "05 Jul 2026, 11:22 PM",
    vehicle: "MH04GH7788",
    driver: "Pranav Mehta",
    location: "Kothrud, Pune",
    recordedSpeed: 12,
    speedLimit: 40,
    status: "Critical",
    type: "sos",
    fleet: "pune",
  },
];
